### PR TITLE
Port to futures 0.3

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
@GuillaumeGomez not sure what's wrong with travis here? I think the check is broken somehow, the submodule is in the right version and in sync with the code. Succeeded apart from that.

**Comment by GuillaumeGomez** [comment]
You need to regen apparently? Check if submodule version matches the one in `version.txt`.

**Comment by sdroege** [comment]
> You need to regen apparently? Check if submodule version matches the one in `version.txt`.

It does and that's exactly the version it should be :)

**Comment by sdroege** [comment]
Oh this is about -sys. Why does this also contain -sys in the same repo?

**Comment by GuillaumeGomez** [comment]
No clue but it does. :3

**Comment by sdroege** [comment]
Fixed and leaving for today :)

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Comment by sdroege** [comment]
@GuillaumeGomez all green now

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
