### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Based on #6
Regen for https://github.com/gtk-rs/glib/pull/196

cc @GuillaumeGomez

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Why is there a commit of mine btw? Where did you get it? XD

**Comment by EPashkin** [comment]
Without your PR sourceview don't builds

**Comment by GuillaumeGomez** [comment]
I completely forgot this PR...

**Comment by EPashkin** [comment]
And branch `fix_features` pushed to upstream too.

**Comment by GuillaumeGomez** [comment]
Thanks! :)

**Pull request merged**
