### PR TITLE
Make CI test sourceview, not examples

### PR DESCRIPTION
**Pull request by EPashkin**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
👍 (Just waiting for CIs and I merge)

**Comment by EPashkin** [comment]
As gkoz's bootstrap don't contains `sourceview`, and I don't know how to fix it, there only 3.10 for travis.

**Comment by GuillaumeGomez** [comment]
Shouldn't it be `v3_10` instead of `gtk_3_10`?

**Comment by EPashkin** [comment]
Updated features

**Comment by EPashkin** [comment]
Ok, travis detect build error only appveyor last.

**Comment by EPashkin** [comment]
appveyor failed too. Ready for merge ;)

**Comment by GuillaumeGomez** [comment]
Haha. Thanks again!

**Pull request merged**
