### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by sdroege**

### CODE REVIEW

**Comment by sdroege** [comment]
Ok this was the last one. In the other crates there are no changes it seems

**Comment by EPashkin** [comment]
I see one line changes in pangocairo, IMHO it can be ignored until 667

**Comment by sdroege** [comment]
> I see one line changes in pangocairo, IMHO it can be ignored until 667

Why don't you comment on https://github.com/gtk-rs/pangocairo/pull/34 ? :) But yes, feel free to just close that one and ignore it for now

**Comment by EPashkin** [comment]
@sdroege Thanks
👍

**Comment by GuillaumeGomez** [comment]
@EPashkin Maybe you're not "watching" the repository?

**Comment by EPashkin** [comment]
No, I watch.
Why you think that?

**Comment by EPashkin** [comment]
Oh it about mail

**Comment by GuillaumeGomez** [comment]
I really don't know. :-/ Try asking github staff directly?

**Comment by EPashkin** [comment]
Yes, I really not watched pangocairo (that strange).

**Comment by sdroege** [comment]
Not sure what that error on CI was, makes no sense (gir submodule and the version.txt were in sync). But I've updated to newer gir now, let's hope it just disappears.

**Comment by sdroege** [comment]
Ok, then let's get this in? @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Yes sir! Thanks!

**Pull request merged**
