### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/pull/490

cc @GuillaumeGomez, @sdroege, @antoyo

### CODE REVIEW

**Comment by EPashkin** [comment]
Seems it need `use gio_ffi` too, despite CI almost passed.

**Comment by EPashkin** [comment]
Updated

**Comment by EPashkin** [comment]
@GuillaumeGomez, there any reason to build `examples` in CI here?
May be better build with `sourceview/v3_18` ?

**Comment by sdroege** [comment]
Looks good to me, just sad that most these now need support for the "progress-callback" pattern used in various async operations

**Comment by EPashkin** [comment]
Forgot add `gio`

**Comment by EPashkin** [comment]
CI passed here too

**Comment by GuillaumeGomez** [comment]
Thanks here too then! 😛

**Pull request merged**
