### PR TITLE
Regen with Ubuntu Discos gir-files

### PR DESCRIPTION
**Pull request by EPashkin**
@GuillaumeGomez Sorry, I forgot that sourceview has good changes in sys.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Not problem, but it will be for the next release.

**Comment by EPashkin** [comment]
@GuillaumeGomez Maybe I remove versions from deps here?

**Comment by GuillaumeGomez** [comment]
I was sure we removed them already. Didn't we @sdroege ? Or did we put them back on purpose?

**Comment by sdroege** [comment]
> @GuillaumeGomez Maybe I remove versions from deps here?

What versions?

**Comment by EPashkin** [comment]
Versions in dependencies https://github.com/gtk-rs/sourceview/blob/master/sourceview-sys/Cargo.toml#L10
we removed it from master in other crates

**Comment by sdroege** [comment]
Yes that's a good idea to remove them

**Pull request merged**
