### PR TITLE
Regen

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @EPashkin 

This one has troubles:

```
error[E0308]: mismatched types
   --> src/auto/search_context.rs:176:99
    |
176 |             let _ = ffi::gtk_source_search_context_backward_finish(_source_object as *mut _, res, &mut match_start, &mut match_end, &mut error);
    |                                                                                                   ^^^^^^^^^^^^^^^^ expected struct `gtk_ffi::GtkTextIter`, found struct `gtk::TextIter`
    |
    = note: expected type `*mut gtk_ffi::GtkTextIter`
               found type `&mut gtk::TextIter`
```

If I recall correctly, we renamed `TextIter` into `GtkTextIter` to avoid some name conflicts. However, is there a way to tell `gir` that it has been renamed or not?

### CODE REVIEW

**Comment by EPashkin** [comment]
You right, it need use `.to_glib_none_mut().0` as in 
```
    #[cfg(any(feature = "v3_22", feature = "dox"))]
    fn backward_finish2<P: IsA<gio::AsyncResult>>(&self, result: &P) -> Result<(gtk::TextIter, gtk::TextIter, bool), Error> {
        unsafe {
            let mut match_start = gtk::TextIter::uninitialized();
            let mut match_end = gtk::TextIter::uninitialized();
            let mut has_wrapped_around = mem::uninitialized();
            let mut error = ptr::null_mut();
            let _ = ffi::gtk_source_search_context_backward_finish2(self.to_glib_none().0, result.to_glib_none().0, match_start.to_glib_none_mut().0, match_end.to_glib_none_mut().0, &mut has_wrapped_around, &mut error);
            if error.is_null() { Ok((match_start, match_end, from_glib(has_wrapped_around))) } else { Err(from_glib_full(error)) }
        }
    }
```

**Comment by EPashkin** [comment]
I will add PR to gir soon

**Comment by EPashkin** [comment]
Added fix.
Also `sourceview` only need build itself in CI

**Comment by ignatenkobrain** [comment]
@EPashkin will you release 0.3.1 once this is fixed? This would be very helpful for me.

**Comment by EPashkin** [comment]
IMHO @GuillaumeGomez will make release, as this really error in published crate.

**Comment by GuillaumeGomez** [comment]
You mean for all crates or just this one?

**Comment by GuillaumeGomez** [comment]
Updated, it fixed the issue. Thanks a lot @EPashkin!

**Comment by EPashkin** [comment]
@GuillaumeGomez will you change CI in this PR?

**Comment by EPashkin** [comment]
IMHO only `sourceview` package need minor update.

**Comment by GuillaumeGomez** [comment]
What requires to be changed in the CI? You want to remove the `build.sh` call and replace it with `cargo build --features v3_24`?

**Comment by EPashkin** [comment]
IMHO appveyor need only 
```
  - pacman --noconfirm -S mingw-w64-%ARCH%-gtksourceview3

build_script:
  - cargo build
  - cargo build --features gtk_3_18
```

Travis need modified copy of `build.sh` as loading custom packages for gtk3.18 still need

**Comment by GuillaumeGomez** [comment]
Do you mind taking care of it please? I'm not sure to fully understand what you have in mind...

**Comment by EPashkin** [comment]
You meant do it in other PR?
Ok.

**Comment by GuillaumeGomez** [comment]
Yes, and thanks! Once done, I'll just restart CIs in here.

**Comment by EPashkin** [comment]
This PR will need not restart CI, but rebase after #37 merged.

**Comment by EPashkin** [comment]
@GuillaumeGomez, you restarted CI but not rebased, so it meaningless

**Comment by GuillaumeGomez** [comment]
I thought it did the tests upon the target branch. I'm a bit disappointed...

**Comment by EPashkin** [comment]
All CI passed new test.

**Comment by GuillaumeGomez** [comment]
Great, let's merge then!

**Comment by EPashkin** [comment]
About publishing minor update: this need update glib too, I will add 2 PR to crate.

**Comment by GuillaumeGomez** [comment]
Sure, go ahead.

**Pull request merged**
