### PR TITLE
Add missing types

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
cc @sdroege @EPashkin

### CODE REVIEW

**Comment by EPashkin** [comment]
I don't see any usage of `ViewGutterPosition` :(
No visible effect for `GLib.Priority` too.

**Comment by GuillaumeGomez** [comment]
There is no usage for `ViewGutterPosition` but at least now it's not missing anymore (I was getting sick of seeing it every time then remember why I didn't add it).

About `GLib.Priority`, it's the not yet available async functions.

**Comment by EPashkin** [comment]
Ok, then 👍

**Comment by GuillaumeGomez** [comment]
Thanks for the review! :)

**Pull request merged**
