### PR TITLE
Use tempfile in tests

### PR DESCRIPTION
**Pull request by EPashkin**
Part of https://github.com/gtk-rs/gir/pull/870

cc @GuillaumeGomez, @sdroege

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
:+1:

**Comment by EPashkin** [comment]
I forgot to update normal version.
Now it updated and travis use rust 1.39 too

**Comment by EPashkin** [comment]
Added reexport gtk's prelude

**Comment by EPashkin** [comment]
CI passed

**Comment by GuillaumeGomez** [comment]
Thanks!

**Pull request merged**
